# Change these first
owner: kenzaflow # Your GitHub organization or username, where this repository lives
repo: grow2on-uptime # The name of this repository

sites:
  - name: Landing
    url: https://grow2on.com/
  - name: Front-End
    url: https://integrador.grow2on.com
  - name: Back-End
    url: https://back.grow2on.com:3102
    __dangerous__insecure: true

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: www.kevinzaracho.com
  baseUrl: /grow2on-uptime
  logoUrl: https://www.kevinzaracho.com/grow2on-uptime/upptime-icon.svg
  favicon: https://www.kevinzaracho.com/grow2on-uptime/upptime-icon.svg
  faviconSvg: https://www.kevinzaracho.com/grow2on-uptime/upptime-icon.svg
  name: Grow2on
  introTitle: 
  introMessage: Uptime
  navbar:
    - title: Status
      href: /grow2on-uptime
    - title: Code
      href: https://github.com/$OWNER/$REPO
    - title: Landing
      href: https://grow2on.com/
  themeUrl: https://www.kevinzaracho.com/grow2on-uptime/theme.css

  i18n:
  footer: Powered by [Wualá](https://wuala.net/)
  
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
