# Change these first
owner: kenzaflow # Your GitHub organization or username, where this repository lives
repo: grow2on-uptime # The name of this repository

sites:
  - name: Front-End
    url: https://integrador.grow2on.com
  - name: Back-End
    url: https://back.grow2on.com:3102
    __dangerous__insecure: true

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: www.kevinzaracho.com
  baseUrl: /grow2on-uptime
  logoUrl: https://raw.githubusercontent.com/kenzaflow/grow2on/master/apple-touch-icon.png
  name: Grow2on
  introTitle: "Uptime de Grow2on"
  introMessage: Website con el uptime de Grow2on
  navbar:
    - title: Estado
      href: /grow2on-uptime
    - title: Código
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
